In [2]:
import pandas as pd
# Used Car Price & Market Analysis
#Cleaning tasks:
#• Convert ₹/lakhs into numeric values
#• Convert mileage and engine values
#• Handle missing values
#• Standardize brand/model names
#• Remove duplicate listings
##• Detect unrealistic mileage/prices
#• Extract numerical information from text

df=pd.read_csv(r"C:\Users\LENOVO\Downloads\cardekho_dataset.csv")
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [3]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [5]:
df.shape

(15411, 14)

In [6]:
df.rename(columns={'Unnamed: 0': 'serial_number'}, inplace=True)

df

,serial_number,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [7]:
df.columns = df.columns.str.title()
df.columns

Index(['Serial_Number', 'Car_Name', 'Brand', 'Model', 'Vehicle_Age',
       'Km_Driven', 'Seller_Type', 'Fuel_Type', 'Transmission_Type', 'Mileage',
       'Engine', 'Max_Power', 'Seats', 'Selling_Price'],
      dtype='object')

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.drop(columns='Serial_Number',inplace=True)
df

,Car_Name,Brand,Model,Vehicle_Age,Km_Driven,Seller_Type,Fuel_Type,Transmission_Type,Mileage,Engine,Max_Power,Seats,Selling_Price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [10]:
df.head(2)

,Car_Name,Brand,Model,Vehicle_Age,Km_Driven,Seller_Type,Fuel_Type,Transmission_Type,Mileage,Engine,Max_Power,Seats,Selling_Price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.7,796,46.3,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.9,1197,82.0,5,550000

In [11]:
# clean car_name columns

df['Car_Name']=df['Car_Name'].str.strip()
df['Car_Name']

0            Maruti Alto
1          Hyundai Grand
2            Hyundai i20
3            Maruti Alto
4          Ford Ecosport
              ...
15406        Hyundai i10
15407      Maruti Ertiga
15408        Skoda Rapid
15409    Mahindra XUV500
15410         Honda City
Name: Car_Name, Length: 15411, dtype: object

In [12]:
df['Car_Name'].duplicated().sum()

np.int64(15290)

In [13]:
# clean brand clean
df['Brand'].unique()

array(['Maruti', 'Hyundai', 'Ford', 'Renault', 'Mini', 'Mercedes-Benz',
       'Toyota', 'Volkswagen', 'Honda', 'Mahindra', 'Datsun', 'Tata',
       'Kia', 'BMW', 'Audi', 'Land Rover', 'Jaguar', 'MG', 'Isuzu',
       'Porsche', 'Skoda', 'Volvo', 'Lexus', 'Jeep', 'Maserati',
       'Bentley', 'Nissan', 'ISUZU', 'Ferrari', 'Mercedes-AMG',
       'Rolls-Royce', 'Force'], dtype=object)

In [14]:
df['Brand'].duplicated().sum()

np.int64(15379)

In [15]:
df['Brand']=df['Brand'].str.title()
df['Brand']

0          Maruti
1         Hyundai
2         Hyundai
3          Maruti
4            Ford
           ...
15406     Hyundai
15407      Maruti
15408       Skoda
15409    Mahindra
15410       Honda
Name: Brand, Length: 15411, dtype: object

In [16]:
## clean Model columns
df['Model']=df['Model'].str.title()
df['Model']

0            Alto
1           Grand
2             I20
3            Alto
4        Ecosport
           ...
15406         I10
15407      Ertiga
15408       Rapid
15409      Xuv500
15410        City
Name: Model, Length: 15411, dtype: object

In [17]:
df['Model'].isnull().sum()

np.int64(0)

In [18]:
df['Model'].duplicated().sum()

np.int64(15291)

In [19]:
df.head(2)

,Car_Name,Brand,Model,Vehicle_Age,Km_Driven,Seller_Type,Fuel_Type,Transmission_Type,Mileage,Engine,Max_Power,Seats,Selling_Price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.7,796,46.3,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.9,1197,82.0,5,550000

In [20]:
# clean Vehicle_Age columns
df['Vehicle_Age'].isna().sum()

np.int64(0)

In [21]:
df['Vehicle_Age'].duplicated().sum()

np.int64(15387)

In [22]:
df['Vehicle_Age'].dtypes

dtype('int64')

In [23]:
## clean Km_Driven columns
df['Km_Driven'].unique()

array([ 120000,   20000,   60000, ...,    9229,   10723, 3800000],
      shape=(3688,))

In [24]:
df[(df['Km_Driven'] <0) |  (df['Km_Driven'] >80000000)].sum()

Car_Name               0
Brand                  0
Model                  0
Vehicle_Age            0
Km_Driven              0
Seller_Type            0
Fuel_Type              0
Transmission_Type      0
Mileage              0.0
Engine                 0
Max_Power            0.0
Seats                  0
Selling_Price          0
dtype: object

In [25]:
df['Km_Driven'].isna().sum()

np.int64(0)

In [26]:
df['Km_Driven'].duplicated().sum()

np.int64(11723)

In [27]:
## clean Seller_Type columns

df['Seller_Type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [28]:
df['Seller_Type']=df['Seller_Type'].str.strip()
df['Seller_Type']

0        Individual
1        Individual
2        Individual
3        Individual
4            Dealer
            ...
15406        Dealer
15407        Dealer
15408        Dealer
15409        Dealer
15410        Dealer
Name: Seller_Type, Length: 15411, dtype: object

In [29]:
df['Seller_Type']=df['Seller_Type'].str.title()
df['Seller_Type']

0        Individual
1        Individual
2        Individual
3        Individual
4            Dealer
            ...
15406        Dealer
15407        Dealer
15408        Dealer
15409        Dealer
15410        Dealer
Name: Seller_Type, Length: 15411, dtype: object

In [30]:
df['Seller_Type'].value_counts()

Seller_Type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [31]:
df['Seller_Type'].isna().sum()

np.int64(0)

In [32]:
df.head(2)

,Car_Name,Brand,Model,Vehicle_Age,Km_Driven,Seller_Type,Fuel_Type,Transmission_Type,Mileage,Engine,Max_Power,Seats,Selling_Price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.7,796,46.3,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.9,1197,82.0,5,550000

In [33]:
## clean Fuel_Type columns

df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [34]:
df['Fuel_Type'].value_counts()

Fuel_Type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [35]:
df['Fuel_Type'].duplicated().sum()

np.int64(15406)

In [36]:
# clean Transmission_Type columns
df['Transmission_Type'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [37]:
df['Transmission_Type'].value_counts()

Transmission_Type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [38]:
df['Transmission_Type'].str.strip()

0           Manual
1           Manual
2           Manual
3           Manual
4           Manual
           ...
15406       Manual
15407       Manual
15408       Manual
15409       Manual
15410    Automatic
Name: Transmission_Type, Length: 15411, dtype: object

In [39]:
## clean Mileage columns
df['Mileage'].unique()

array([19.7 , 18.9 , 17.  , 20.92, 22.77, 20.36, 20.51, 18.15, 16.6 ,
       22.32, 19.64, 14.41, 28.09, 25.2 , 19.27, 28.4 , 12.99, 21.4 ,
       20.85, 16.09, 19.67, 17.4 , 13.6 , 26.59, 17.7 , 17.19, 13.  ,
       23.01, 18.6 , 17.92, 15.1 , 23.4 , 22.54, 18.  , 21.  , 15.4 ,
       20.89, 26.6 , 22.5 , 17.8 , 20.54, 17.3 , 25.  , 24.  , 18.16,
       21.21, 14.  , 16.8 , 25.17, 24.3 , 18.5 , 23.84, 18.78, 11.74,
       25.1 , 21.01, 22.74, 21.9 , 15.6 , 19.1 , 22.07, 22.  , 23.1 ,
       23.  , 19.08, 18.27, 23.9 , 16.1 , 19.81, 19.44, 18.59, 20.62,
       17.01, 17.5 , 12.05, 25.83, 21.79, 13.7 , 16.47, 20.7 , 10.91,
       25.8 , 25.32, 19.87, 18.7 , 14.4 , 22.69, 20.73, 16.55, 20.  ,
       21.5 , 24.7 , 23.95, 21.63, 17.43, 25.47, 33.54, 15.96, 21.19,
       26.  , 12.55, 16.9 , 22.3 , 12.9 , 13.5 , 17.84, 27.28, 24.04,
       22.7 , 16.  , 17.6 , 21.7 , 20.45, 17.14, 19.6 , 20.4 , 12.63,
       17.1 , 15.37, 11.4 , 13.68, 17.68, 12.3 , 12.19, 17.33, 20.77,
       12.07, 20.3 , 27.39, 16.36, 15.8 , 11.29, 20.52, 31.79,  9.17,
       20.8 , 14.28, 19.3 , 26.21, 18.1 , 22.9 , 14.94, 13.38, 17.41,
       11.5 , 17.03, 18.2 , 13.9 , 12.4 , 19.34, 15.81, 14.21, 15.15,
       19.01, 18.12, 30.46, 17.05, 21.94, 24.52, 15.  , 19.  , 13.14,
       14.84, 26.2 , 20.63, 10.26, 14.7 , 33.44, 17.2 , 23.26, 11.36,
       17.99, 21.13, 20.68, 15.26, 11.57, 19.12, 22.05, 11.8 , 13.93,
       16.93, 13.2 , 18.25, 26.32, 19.83, 22.37,  9.5 , 19.16, 16.7 ,
       27.3 , 19.5 , 20.14, 19.62, 22.27, 32.52, 11.3 , 15.74, 16.2 ,
       24.4 , 18.69, 15.04, 17.66, 12.  , 15.29, 14.3 , 10.1 , 16.02,
       15.85, 14.49, 16.5 , 22.48, 22.1 , 15.2 , 10.  , 14.62, 23.7 ,
       12.7 , 10.75, 21.38, 20.28, 11.33, 20.5 , 17.11, 22.15, 11.1 ,
        8.45, 20.41, 10.5 , 21.14,  9.52, 24.2 , 18.48, 18.88, 20.34,
       12.8 , 11.79, 25.5 , 11.88, 12.5 , 19.72, 14.23, 14.1 , 14.12,
       11.25, 13.33, 13.4 , 16.38, 13.96, 19.56, 11.  , 15.9 , 27.62,
       19.95, 13.1 , 20.46, 12.39, 27.4 , 18.23, 22.8 , 14.59, 18.19,
       14.8 , 23.8 , 20.65, 19.4 , 20.64, 26.83, 26.1 , 14.67, 19.59,
       12.81, 26.8 , 10.8 , 17.21, 18.56, 17.9 , 16.95, 21.66, 26.08,
       12.98, 18.24, 18.53, 12.1 ,  7.81, 26.55, 18.06, 13.45, 11.7 ,
       30.48, 21.3 , 14.04, 20.04, 30.47, 12.97, 16.4 , 16.07, 14.24,
       21.76, 21.49, 21.27, 14.71, 11.49, 21.56, 19.71, 16.73, 16.11,
       14.5 , 19.02, 14.75, 25.6 , 24.07, 19.33, 10.13, 16.05, 10.93,
       24.12, 24.8 , 13.24, 14.69, 12.35, 20.2 , 21.74, 15.63, 21.1 ,
       14.74, 15.34, 23.5 , 24.29, 15.5 , 16.77, 14.19, 15.11, 18.76,
       19.2 , 17.09, 16.46, 13.8 , 20.88, 16.3 , 15.97,  4.  ,  9.26,
       12.65, 15.3 , 20.35, 14.42, 20.71, 15.64, 19.39, 14.6 , 10.9 ,
        9.  , 21.72, 32.26,  7.5 , 23.87, 19.23, 26.82, 12.51, 15.68,
       15.06, 14.57,  9.3 , 12.6 , 11.2 , 12.83, 10.2 , 19.05, 12.62,
       10.37, 18.32, 19.91, 18.57, 15.41,  8.9 , 14.11,  8.5 , 11.9 ,
       16.78, 18.3 ,  7.94, 10.6 , 18.8 , 11.78,  6.  , 17.54, 11.31,
       17.85, 18.4 , 24.1 , 14.38, 10.4 , 15.01, 17.24, 13.29, 19.19,
       20.6 ,  8.77, 17.61, 18.42, 12.95, 14.99, 15.92,  8.6 , 17.69,
       16.12, 18.84, 19.65, 17.74, 17.18, 13.53])

In [40]:
df['Mileage']=pd.to_numeric(df['Mileage'],errors='coerce')
df['Mileage']

0        19.70
1        18.90
2        17.00
3        20.92
4        22.77
         ...
15406    19.81
15407    17.50
15408    21.14
15409    16.00
15410    18.00
Name: Mileage, Length: 15411, dtype: float64

In [41]:
df['Mileage'].dtype

dtype('float64')

In [42]:
df['Mileage'].isna().sum()

np.int64(0)

In [43]:
df = df[(df['Mileage'] > 0) & (df['Mileage'] < 100)]
df

,Car_Name,Brand,Model,Vehicle_Age,Km_Driven,Seller_Type,Fuel_Type,Transmission_Type,Mileage,Engine,Max_Power,Seats,Selling_Price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,I20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,Hyundai i10,Hyundai,I10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,Mahindra XUV500,Mahindra,Xuv500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [44]:
df['Mileage']=df['Mileage'].astype(int)
df['Mileage']

0        19
1        18
2        17
3        20
4        22
         ..
15406    19
15407    17
15408    21
15409    16
15410    18
Name: Mileage, Length: 15411, dtype: int64

In [45]:
df.head(2)

,Car_Name,Brand,Model,Vehicle_Age,Km_Driven,Seller_Type,Fuel_Type,Transmission_Type,Mileage,Engine,Max_Power,Seats,Selling_Price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19,796,46.3,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18,1197,82.0,5,550000

In [46]:
# clean Engine columns

df['Engine'].unique()

array([ 796, 1197,  998, 1498, 1582, 1461, 1998, 1248, 2143, 2494, 1598,
       1497, 2523, 2982,  999, 1199, 1086, 2179, 1396, 1198, 1590, 1997,
       1493, 1120, 1196, 1186, 1061,  799, 1796, 2993, 1298, 3198, 1995,
       1373, 1591, 1968, 1399, 1047, 1353, 2755, 1395, 2498, 1999, 2953,
       2393, 2967, 2998, 2995, 1956, 1462, 1799, 2499, 1451, 1194, 1798,
       2694, 1496, 1969, 2487, 3604, 1499, 2987, 1599, 2354, 1950, 2148,
       4134, 2400, 1984, 2979, 2609, 2092, 5998, 1330, 2956, 3598, 2362,
        793, 1368, 3597, 1991, 5461, 1343, 2497, 4367, 1797, 3498, 2698,
       1896, 2999, 3855, 4806, 1985, 2771, 2157, 3628, 2198, 2996, 2199,
       4395, 3456, 4663, 2773, 6592, 2495, 1781, 2997, 1597, 2596, 4163])

In [47]:
df['Engine'] = df['Engine'].astype('string') + ' cc'
df['Engine']

0         796 cc
1        1197 cc
2        1197 cc
3         998 cc
4        1498 cc
          ...
15406    1086 cc
15407    1373 cc
15408    1498 cc
15409    2179 cc
15410    1497 cc
Name: Engine, Length: 15411, dtype: string

In [48]:
df.head(5)

,Car_Name,Brand,Model,Vehicle_Age,Km_Driven,Seller_Type,Fuel_Type,Transmission_Type,Mileage,Engine,Max_Power,Seats,Selling_Price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19,796 cc,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18,1197 cc,82.00,5,550000
2,Hyundai i20,Hyundai,I20,11,60000,Individual,Petrol,Manual,17,1197 cc,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20,998 cc,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22,1498 cc,98.59,5,570000

In [49]:
df['Engine'].isna().sum()

np.int64(0)

In [50]:
# clean Max_Power columns
df['Max_Power'].value_counts()

Max_Power
74.00     791
88.50     589
81.80     544
98.60     424
67.04     390
         ...
450.00      1
258.81      1
459.00      1
151.89      1
177.01      1
Name: count, Length: 342, dtype: int64

In [51]:
df['Max_Power'].duplicated().sum()

np.int64(15069)

In [52]:
# clean Seats columns
df['Seats'].value_counts()

Seats
5    12910
7     1922
8      311
6      127
4       77
9       55
2        7
0        2
Name: count, dtype: int64

In [53]:
df['Seats'].isna().sum()

np.int64(0)

In [54]:
## clean Selling_Price columns
df['Selling_Price'].unique()

array([ 120000,  550000,  215000, ..., 1640000,  386000,  456000],
      shape=(1086,))

In [55]:
df['Selling_Price'].isna().sum()

np.int64(0)

In [56]:
df.to_csv('car_data_clean.csv', index=False)

In [57]:
df

,Car_Name,Brand,Model,Vehicle_Age,Km_Driven,Seller_Type,Fuel_Type,Transmission_Type,Mileage,Engine,Max_Power,Seats,Selling_Price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19,796 cc,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18,1197 cc,82.00,5,550000
2,Hyundai i20,Hyundai,I20,11,60000,Individual,Petrol,Manual,17,1197 cc,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20,998 cc,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22,1498 cc,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,Hyundai i10,Hyundai,I10,9,10723,Dealer,Petrol,Manual,19,1086 cc,68.05,5,250000
15407,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17,1373 cc,91.10,7,925000
15408,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21,1498 cc,103.52,5,425000
15409,Mahindra XUV500,Mahindra,Xuv500,5,3800000,Dealer,Diesel,Manual,16,2179 cc,140.00,7,1225000
15410,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18,1497 cc,117.60,5,1200000